version: '3.8'
services:
  gateway:
    build: ./gateway
    #image:
    #  - share-it-gateway-image
    #container_name:
    #  - share-it-gateway-container
    ports:
      - "8090:8090"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:8080

  server:
    build: ./server
    #image:
    #  - share-it-server-image
    #container_name:
    #  - share-it-server-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    #container_name:
    #  - share-it-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root