drop table if exists bookings;

drop table if exists comments;

drop table if exists items;

drop table if exists requests;

drop table if exists users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_requests
        PRIMARY KEY (id),
    CONSTRAINT fk_requests
        FOREIGN KEY (requestor_id) REFERENCES users ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT DEFAULT NULL,
    CONSTRAINT pk_items
        PRIMARY KEY (id),
    CONSTRAINT fk_items_1
        FOREIGN KEY (owner_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT fk_items_2
        FOREIGN KEY (request_id) REFERENCES requests ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status     VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_bookings
        PRIMARY KEY (id),
    CONSTRAINT fk_bookings_1
        FOREIGN KEY (item_id) REFERENCES items ON DELETE CASCADE,
    CONSTRAINT fk_bookings_2
        FOREIGN KEY (booker_id) REFERENCES users ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(512)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments
        PRIMARY KEY (id),
    CONSTRAINT fk_comments_1
        FOREIGN KEY (item_id) REFERENCES items ON DELETE CASCADE,
    CONSTRAINT fk_comments_2
        FOREIGN KEY (author_id) REFERENCES users ON DELETE CASCADE
);
